name: 'Action Changelog Generator'
description: 'Generator a Changelog file and create a pull request.'
inputs:
  repo-token:
    description: 'repo token to create a pr'
    required: true
  repo-name:
    description: 'repo name to create a pr'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
