name: 'Action Changelog Generator'
description: 'Generator a Changelog file and create a pull request.'
inputs:
  repo-token:
    description: 'repo token to create a pr'
    required: true
  repo-name:
    description: 'repo name to create a pr and generate the change log'
    required: true
  repo-user:
      description: 'repo user to generate the change log'
      required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo-token }}
