FROM ferrarimarco/github-changelog-generator

COPY entrypoint.sh /entrypoint.sh
COPY . /usr/local/src/your-app

RUN apk add --update \
    curl \
    && rm -rf /var/cache/apk/*


ENTRYPOINT ["sh","/entrypoint.sh" ,"a" ,"action-changelog-generator", "viniciusCSreis"]
