name: "units-test"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:

  # test action works running from the graph  
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        repo-name: action-changelog-generator
        repo-user: viniciusCSreis