name: "units-test"
on:
  push:
    branches:
      - master
  pull_request:
    branches: [ master ]

jobs:

  # test action works running from the graph  
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        base-branch: master
        changelog-branch: changelog
